//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activities_Inspector {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activities_Inspector.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione! L&apos;orario del PC potrebbe essere stato modificato oppure il server NTP non è raggiungibile.
        ///Per verificare eventuali modifiche all&apos;orario di sistema consultare la sezione &quot;MODIFICHE ALL&apos;ORA DI SISTEMA&quot;..
        /// </summary>
        public static string App_DateTime_Error_Message {
            get {
                return ResourceManager.GetString("App_DateTime_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Inspector.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esportazione conclusa con successo..
        /// </summary>
        public static string ExportCommand_ExportComplete_Message {
            get {
                return ResourceManager.GetString("ExportCommand_ExportComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmi installati.
        /// </summary>
        public static string InstalledPrograms_FileName {
            get {
                return ResourceManager.GetString("InstalledPrograms_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accensione - Spegnimento.
        /// </summary>
        public static string Intervals_FileName {
            get {
                return ResourceManager.GetString("Intervals_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        public static string MainWindow_Report_Button_Content {
            get {
                return ResourceManager.GetString("MainWindow_Report_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string MainWindow_Usb_DeviceName {
            get {
                return ResourceManager.GetString("MainWindow_Usb_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome macchina.
        /// </summary>
        public static string MainWindow_Usb_MachineName {
            get {
                return ResourceManager.GetString("MainWindow_Usb_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserimento.
        /// </summary>
        public static string MainWindow_Usb_PluggedTime {
            get {
                return ResourceManager.GetString("MainWindow_Usb_PluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string MainWindow_Usb_ProductId {
            get {
                return ResourceManager.GetString("MainWindow_Usb_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string MainWindow_Usb_SerialNumber {
            get {
                return ResourceManager.GetString("MainWindow_Usb_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string MainWindow_Usb_State {
            get {
                return ResourceManager.GetString("MainWindow_Usb_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rimozione.
        /// </summary>
        public static string MainWindow_Usb_UnpluggedTime {
            get {
                return ResourceManager.GetString("MainWindow_Usb_UnpluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe.
        /// </summary>
        public static string MainWindow_Usb_UsbClass {
            get {
                return ResourceManager.GetString("MainWindow_Usb_UsbClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VID.
        /// </summary>
        public static string MainWindow_Usb_VendorId {
            get {
                return ResourceManager.GetString("MainWindow_Usb_VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAMMI INSTALLATI.
        /// </summary>
        public static string MainWindow_ViewerMode_InstalledPrograms {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_InstalledPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFETCH.
        /// </summary>
        public static string MainWindow_ViewerMode_Prefetch {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Prefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE RECENTI.
        /// </summary>
        public static string MainWindow_ViewerMode_Recents {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGON/LOGOFF.
        /// </summary>
        public static string MainWindow_ViewerMode_Sessions {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHELLBAGS.
        /// </summary>
        public static string MainWindow_ViewerMode_ShellBags {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_ShellBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICHE ALL&apos;ORA DI SISTEMA.
        /// </summary>
        public static string MainWindow_ViewerMode_SystemTimeChanged {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_SystemTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCENSIONE/SPEGNIMENTO.
        /// </summary>
        public static string MainWindow_ViewerMode_TimeIntervals {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_TimeIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERIFERICHE USB.
        /// </summary>
        public static string MainWindow_ViewerMode_Usb {
            get {
                return ResourceManager.GetString("MainWindow_ViewerMode_Usb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esporta.
        /// </summary>
        public static string MainWindows_ExportCommand_Content {
            get {
                return ResourceManager.GetString("MainWindows_ExportCommand_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgente.
        /// </summary>
        public static string MainWindows_InstallEntry_DataSource {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome file.
        /// </summary>
        public static string MainWindows_InstallEntry_FileName {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso.
        /// </summary>
        public static string MainWindows_InstallEntry_FullPath {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MainWindows_InstallEntry_installDate {
            get {
                return ResourceManager.GetString("MainWindows_InstallEntry_installDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string MainWindows_LoadCommand_Content {
            get {
                return ResourceManager.GetString("MainWindows_LoadCommand_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome file.
        /// </summary>
        public static string MainWindows_Prefetch_ExecutableFileName {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_ExecutableFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estensione.
        /// </summary>
        public static string MainWindows_Prefetch_Extension {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ultima esecuzione.
        /// </summary>
        public static string MainWindows_Prefetch_LastRunTime {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_LastRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgente.
        /// </summary>
        public static string MainWindows_Prefetch_SourceFileName {
            get {
                return ResourceManager.GetString("MainWindows_Prefetch_SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MainWindows_RecentFolder_ActionTime {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_ActionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorgente.
        /// </summary>
        public static string MainWindows_RecentFolder_DataSource {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome file.
        /// </summary>
        public static string MainWindows_RecentFolder_FileName {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso .
        /// </summary>
        public static string MainWindows_RecentFolder_FullPath {
            get {
                return ResourceManager.GetString("MainWindows_RecentFolder_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di accesso.
        /// </summary>
        public static string MainWindows_Sessions_AccessType {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata.
        /// </summary>
        public static string MainWindows_Sessions_Duration {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominio.
        /// </summary>
        public static string MainWindows_Sessions_Group {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora di disconnessione.
        /// </summary>
        public static string MainWindows_Sessions_LogOffTime {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_LogOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora di accesso.
        /// </summary>
        public static string MainWindows_Sessions_LogOnTime {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_LogOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome macchina.
        /// </summary>
        public static string MainWindows_Sessions_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo di rete.
        /// </summary>
        public static string MainWindows_Sessions_NetworkAddress {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_NetworkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente.
        /// </summary>
        public static string MainWindows_Sessions_UserName {
            get {
                return ResourceManager.GetString("MainWindows_Sessions_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso.
        /// </summary>
        public static string MainWindows_ShellBags_AbsolutePath {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_AbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data accesso.
        /// </summary>
        public static string MainWindows_ShellBags_AccessedDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_AccessedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di creazione.
        /// </summary>
        public static string MainWindows_ShellBags_CreationDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ultima scrittura.
        /// </summary>
        public static string MainWindows_ShellBags_LastRegistryWriteDate {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_LastRegistryWriteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percorso nel registro.
        /// </summary>
        public static string MainWindows_ShellBags_RegistryPath {
            get {
                return ResourceManager.GetString("MainWindows_ShellBags_RegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_DeviceName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora evento.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_EventTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome macchina.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo orario.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_NewTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_NewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vecchio orario.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_OldTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_OldTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inserimento.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_PluggedTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_PluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rimozione.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_UnpluggedTime {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_UnpluggedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MainWindows_SystemTimeChanged_UserName {
            get {
                return ResourceManager.GetString("MainWindows_SystemTimeChanged_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata.
        /// </summary>
        public static string MainWindows_TimeIntervals_Duration {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spegnimento.
        /// </summary>
        public static string MainWindows_TimeIntervals_End {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome macchina.
        /// </summary>
        public static string MainWindows_TimeIntervals_MachineName {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accensione.
        /// </summary>
        public static string MainWindows_TimeIntervals_Start {
            get {
                return ResourceManager.GetString("MainWindows_TimeIntervals_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefetch.
        /// </summary>
        public static string Prefetch_FileName {
            get {
                return ResourceManager.GetString("Prefetch_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File recenti.
        /// </summary>
        public static string Recents_FileName {
            get {
                return ResourceManager.GetString("Recents_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione caso.
        /// </summary>
        public static string ReportWindow_Description_Group_Surname {
            get {
                return ResourceManager.GetString("ReportWindow_Description_Group_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERIZIA.
        /// </summary>
        public static string ReportWindow_Expertise_Value {
            get {
                return ResourceManager.GetString("ReportWindow_Expertise_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genera report.
        /// </summary>
        public static string ReportWindow_GenerateReport_Button_Content {
            get {
                return ResourceManager.GetString("ReportWindow_GenerateReport_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigatore.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Header {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Name {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifica.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Qualification {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string ReportWindow_Inquirer_Group_Surname {
            get {
                return ResourceManager.GetString("ReportWindow_Inquirer_Group_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULENZA TECNICA D&apos;UFFICIO.
        /// </summary>
        public static string ReportWindow_OfficialTechnicalConsultancy_Value {
            get {
                return ResourceManager.GetString("ReportWindow_OfficialTechnicalConsultancy_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro:.
        /// </summary>
        public static string ReportWindow_Other_Value {
            get {
                return ResourceManager.GetString("ReportWindow_Other_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARERE PRO VERITATE.
        /// </summary>
        public static string ReportWindow_ParereProveritate_Value {
            get {
                return ResourceManager.GetString("ReportWindow_ParereProveritate_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSULENZA TECNICA DI PARTE.
        /// </summary>
        public static string ReportWindow_TechnicalConsultancy_Value {
            get {
                return ResourceManager.GetString("ReportWindow_TechnicalConsultancy_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Inspector - Report.
        /// </summary>
        public static string ReportWindow_Title {
            get {
                return ResourceManager.GetString("ReportWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione completata con successo!.
        /// </summary>
        public static string ReportWindows_OperationComplete_Info {
            get {
                return ResourceManager.GetString("ReportWindows_OperationComplete_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch (4).
        /// </summary>
        public static string Sessions_AccessType_Batch {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tipo di accesso batch viene utilizzato dai server batch, in cui i processi possono essere esecutori per conto di un utente senza l&apos;intervento diretto..
        /// </summary>
        public static string Sessions_AccessType_Batch_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Batch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached Interactive (11).
        /// </summary>
        public static string Sessions_AccessType_CachedInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utente ha eseguito l&apos;accesso al computer con credenziali di rete archiviate localmente nel computer. Il controller di dominio non è stato contattato per verificare le credenziali..
        /// </summary>
        public static string Sessions_AccessType_CachedInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached Remote Interactive (12).
        /// </summary>
        public static string Sessions_AccessType_CachedRemoteInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedRemoteInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utente ha eseguito l&apos;accesso a questo computer in remoto utilizzando Servizi terminal o Desktop remoto.. Viene utilizzato per il controllo interno..
        /// </summary>
        public static string Sessions_AccessType_CachedRemoteInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedRemoteInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached Unlock (13).
        /// </summary>
        public static string Sessions_AccessType_CachedUnlock {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accesso workstation..
        /// </summary>
        public static string Sessions_AccessType_CachedUnlock_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_CachedUnlock_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive (2).
        /// </summary>
        public static string Sessions_AccessType_Interactive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Interactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utente ha eseguito l&apos;accesso al computer..
        /// </summary>
        public static string Sessions_AccessType_Interactive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_Interactive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Cleartext (8).
        /// </summary>
        public static string Sessions_AccessType_NetworkCleartext {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NetworkCleartext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utente ha eseguito l&apos;accesso al computer dalla rete. La password dell&apos;utente è stata passata al pacchetto di autenticazione nel formato non crittografato. L&apos;autenticazione incorporata in pacchetto tutte le credenziali hash prima di inviarle attraverso la rete. Le credenziali non attraversano la rete in testo normale (detto anche testo non crittografato)..
        /// </summary>
        public static string Sessions_AccessType_NetworkClearText_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NetworkClearText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Credentials (9).
        /// </summary>
        public static string Sessions_AccessType_NewCredentials {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NewCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un chiamante ha clonato il token corrente e specificato nuove credenziali per le connessioni in uscita. La nuova sessione di accesso ha la stessa identità locale, ma utilizza credenziali diverse per altre connessioni di rete..
        /// </summary>
        public static string Sessions_AccessType_NewCredentials_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_NewCredentials_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Interactive (10).
        /// </summary>
        public static string Sessions_AccessType_RemoteInteractive {
            get {
                return ResourceManager.GetString("Sessions_AccessType_RemoteInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un utente ha eseguito l&apos;accesso a questo computer in remoto utilizzando Servizi terminal o Desktop remoto..
        /// </summary>
        public static string Sessions_AccessType_RemoteInteractive_Tooltip {
            get {
                return ResourceManager.GetString("Sessions_AccessType_RemoteInteractive_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessioni.
        /// </summary>
        public static string Sessions_FileName {
            get {
                return ResourceManager.GetString("Sessions_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellBags.
        /// </summary>
        public static string ShellBags_FileName {
            get {
                return ResourceManager.GetString("ShellBags_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome utente.
        /// </summary>
        public static string SystemTimeChanged_AccountName_ColumnHeader {
            get {
                return ResourceManager.GetString("SystemTimeChanged_AccountName_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiche all&apos;ora di sistema.
        /// </summary>
        public static string SystemTimeChanged_FileName {
            get {
                return ResourceManager.GetString("SystemTimeChanged_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo orario.
        /// </summary>
        public static string SystemTimeChanged_NewTime_ColumnHeader {
            get {
                return ResourceManager.GetString("SystemTimeChanged_NewTime_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orario precedente.
        /// </summary>
        public static string SystemTimeChanged_OldTime_ColumnHeader {
            get {
                return ResourceManager.GetString("SystemTimeChanged_OldTime_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ora evento.
        /// </summary>
        public static string SystemTimeChanged_TimeGenerated_ColumnHeader {
            get {
                return ResourceManager.GetString("SystemTimeChanged_TimeGenerated_ColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usb.
        /// </summary>
        public static string Usb_FileName {
            get {
                return ResourceManager.GetString("Usb_FileName", resourceCulture);
            }
        }
    }
}
